[project]
name = "data_pipeline"
version = "0.1.0"
description = "Python-first ELT pipeline: Bronze→Silver in Python, Silver→Gold in Postgres"
requires-python = ">=3.10"

[tool]
# add black/ruff/pytest configs as needed
